-- Gui to Lua
-- Version: 3.2

-- Instances:

local Spawner = Instance.new("ScreenGui")
local TextButton = Instance.new("TextButton")
local TextButton_2 = Instance.new("TextButton")

--Properties:

Spawner.Name = "Spawner"
Spawner.Parent = game.Players.LocalPlayer:WaitForChild("PlayerGui")
Spawner.ZIndexBehavior = Enum.ZIndexBehavior.Sibling

TextButton.Parent = Spawner
TextButton.BackgroundColor3 = Color3.fromRGB(47, 47, 47)
TextButton.Position = UDim2.new(0.845752597, 0, 0.605442226, 0)
TextButton.Size = UDim2.new(0, 162, 0, 71)
TextButton.Font = Enum.Font.Cartoon
TextButton.Text = "Spawner"
TextButton.TextColor3 = Color3.fromRGB(255, 255, 255)
TextButton.TextScaled = true
TextButton.TextSize = 14.000
TextButton.TextWrapped = true

TextButton_2.Parent = Spawner
TextButton_2.BackgroundColor3 = Color3.fromRGB(47, 47, 47)
TextButton_2.Position = UDim2.new(0.845752597, 0, 0.758503437, 0)
TextButton_2.Size = UDim2.new(0, 162, 0, 71)
TextButton_2.Font = Enum.Font.Cartoon
TextButton_2.Text = "Destroy"
TextButton_2.TextColor3 = Color3.fromRGB(255, 255, 255)
TextButton_2.TextScaled = true
TextButton_2.TextSize = 14.000
TextButton_2.TextWrapped = true

-- Scripts:

local function ECLLMA_fake_script() -- TextButton.Script 
	local script = Instance.new('Script', TextButton)

	_G.toggle = false
	
	script.Parent.MouseButton1Click:Connect(function()
		if _G.toggle == false then
			script.Parent.Text = "Spawner on"
			_G.toggle = true
		else
			script.Parent.Text = "Spawner off"
			_G.toggle = false
		end
		while _G.toggle == true do
			wait()
			-- Script generated by SimpleSpy - credits to exx#9394
	
			local args = {
				[1] = "BOSS_SUMMONING",
				[2] = "Twice"
			}
	
			game:GetService("ReplicatedStorage").Remotes.Input:FireServer(unpack(args))
	
		end
	end)
end
coroutine.wrap(ECLLMA_fake_script)()
local function YLRBBLQ_fake_script() -- TextButton_2.Script 
	local script = Instance.new('Script', TextButton_2)

	script.Parent.MouseButton1Click:Connect(function()
		game.Players.LocalPlayer.PlayerGui.Spawner:Destroy()
	end)
end
coroutine.wrap(YLRBBLQ_fake_script)()
